version: '3.11'
services:


  db:
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


  backend:
    image: sergeykataev1/foodgram-backend
    ports:
      - 8000:80
    restart: always
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env


  frontend:
    image: sergeykataev1/foodgram-frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db


  nginx:
    image: nginx:1.25.1
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend


volumes:
  db_data:
  static_value:
  media_value: